version: '3'

services:
  ichaindnode0:
    container_name: ichaindnode0
    image: "icheckteam/ichaindnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=$${LOG:-ichaind.log}
    volumes:
      - ./build:/ichaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  ichaindnode1:
    container_name: ichaindnode1
    image: "icheckteam/ichaindnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=$${LOG:-ichaind.log}
    volumes:
      - ./build:/ichaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  ichaindnode2:
    container_name: ichaindnode2
    image: "icheckteam/ichaindnode"
    environment:
      - ID=2
      - LOG=$${LOG:-ichaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/ichaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  ichaindnode3:
    container_name: ichaindnode3
    image: "icheckteam/ichaindnode"
    environment:
      - ID=3
      - LOG=$${LOG:-ichaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/ichaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
subnet: 192.168.10.0/16